# Generated by Django 5.0.4 on 2024-04-20 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_keylogin_delete_service"),
    ]

    operations = [
        migrations.AlterField(
            model_name="keylogin",
            name="key",
            field=models.CharField(unique=True, verbose_name="Открытый ключ сервиса"),
        ),
    ]
