# Generated by Django 5.0.4 on 2024-04-20 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_keylogin_key"),
        ("users", "0003_edituser"),
    ]

    operations = []
