# Generated by Django 5.0.4 on 2024-04-21 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_merge_0003_alter_keylogin_key_0003_edituser"),
    ]

    operations = [
        migrations.DeleteModel(
            name="KeyLogin",
        ),
    ]
