version: '3.7'

services:
  db:
    image: 'postgres:12.4'
    environment: 
        POSTGRES_DB: db
        POSTGRES_USER: developer
        POSTGRES_PASSWORD: Passw0rd33
    volumes:
      - ./db:/var/lib/postgresql/data

  web:
    volumes:
      - ./kernel:/app
      - ./kernel/static:/app/static
      - ./kernel/media:/app/media
    env_file:
      - ./kernel/.env
    build: ./kernel
    ports:
      - '8000:8000'
    depends_on:
      - db

  nginx:
    image: staticfloat/nginx-certbot
    depends_on:
      - web
    volumes:
      - ./kernel/static:/var/www/html/static
      - ./nginx/conf.d:/etc/nginx/user.conf.d:ro
      - letsencrypt:/etc/letsencrypt
#      - www-html:/var/www/html
    environment:
      CERTBOT_EMAIL: adrian.makridenko@proton.me
    ports:
      - 80:80/tcp
      - 443:443/tcp

volumes:
  static:
