# Generated by Django 5.0.4 on 2024-04-21 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0004_merge_0003_alter_keylogin_key_0003_edituser"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrivateKeys",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service", models.URLField(verbose_name="link to service")),
                ("public_key", models.CharField(verbose_name="Публичный ключ")),
                (
                    "private_key",
                    models.CharField(
                        blank=True,
                        null=True,
                        verbose_name="Зашифрованный приватный ключ",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.profile"
                    ),
                ),
            ],
        ),
    ]
