name: Деплой на dev-сервер
on:
  push:
    branches: [ develop ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Деплой на dev сервер
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: adrian
          key: ${{ secrets.ID_RSA }}
          script: |
            cd passal
            git pull
            ./deploy.sh dev
